version: "2"

linters:
  enable:
    - errcheck
    - govet
    - staticcheck
    - gosimple
    - unused
    - ineffassign
    - gocritic
    - gofmt
    - goimports
    - gosec
    - nilerr
    - errorlint
    - bodyclose

linters-settings:
  errcheck:
    exclude-functions:
      - fmt.Fprintf
      - fmt.Fprintln
      - fmt.Printf
      - fmt.Println
      - (os.File).Close
  gocritic:
    enabled-tags:
      - diagnostic
      - style
    disabled-checks:
      - ifElseChain
      - hugeParam
  gosec:
    excludes:
      - G101
      - G304

issues:
  max-issues-per-linter: 0
  max-same-issues: 0
