version: 2
project_name: ipriver

before:
  hooks:
    - go mod tidy
    - go test ./...

builds:
  - env:
      - CGO_ENABLED=0
    goos:
      - darwin
      - linux
      - windows
    goarch:
      - amd64
      - arm64
    ignore:
      - goos: windows
        goarch: arm64
    ldflags:
      - -s -w
      - -X main.version={{.Version}}
      - -X main.commit={{.Commit}}
      - -X main.date={{.Date}}
    main: .
    binary: ipriver

archives:
  - format: tar.gz
    name_template: "{{ .ProjectName }}_{{ .Version }}_{{ .Os }}_{{ .Arch }}"
    format_overrides:
      - goos: windows
        format: zip
    files:
      - README.md
      - LICENSE*

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ incpatch .Version }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"

release:
  github:
    owner: ipriverdev
    name: cli
  draft: false
  prerelease: auto

brews:
  - name: ipriver
    repository:
      owner: ipriverdev
      name: cli
    directory: Formula
    homepage: "https://github.com/ipriverdev/cli"
    description: "The ipriver command-line tool"
    install: |
      bin.install "ipriver"
      bin.install_symlink "ipriver" => "ipr"
    test: |
      system "#{bin}/ipriver", "version"
