# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipriver < Formula
  desc "The ipriver command-line tool"
  homepage "https://github.com/ipriverdev/cli"
  version "0.1.3"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ipriverdev/cli/releases/download/v0.1.3/ipriver_0.1.3_darwin_amd64.tar.gz"
      sha256 "51e1337bbe006bb5432fe46955ec020e3e5abfd5e12f0df51c9b3f5c0753b45f"

      define_method(:install) do
        bin.install "ipriver"
        bin.install_symlink "ipriver" => "ipr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ipriverdev/cli/releases/download/v0.1.3/ipriver_0.1.3_darwin_arm64.tar.gz"
      sha256 "0f7a4a26a6f42ad17de62b00b20f1ae927fbb1c5c643627a10fba69428834eee"

      define_method(:install) do
        bin.install "ipriver"
        bin.install_symlink "ipriver" => "ipr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipriverdev/cli/releases/download/v0.1.3/ipriver_0.1.3_linux_amd64.tar.gz"
      sha256 "3d9b3fcc418f67d4cfed1fb4093a406f716dfad353661dcd30bd5cc5f486f570"
      define_method(:install) do
        bin.install "ipriver"
        bin.install_symlink "ipriver" => "ipr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipriverdev/cli/releases/download/v0.1.3/ipriver_0.1.3_linux_arm64.tar.gz"
      sha256 "5d75a6b38c8fb99d4b363ab0b326fcbb60df4ed39fd10478f8e327b17b05c22e"
      define_method(:install) do
        bin.install "ipriver"
        bin.install_symlink "ipriver" => "ipr"
      end
    end
  end

  test do
    system "#{bin}/ipriver", "version"
  end
end
