# typed: false
# frozen_string_literal: true

# This file was generated by GoReleaser. DO NOT EDIT.
class Ipriver < Formula
  desc "The ipriver command-line tool"
  homepage "https://github.com/ipriverdev/cli"
  version "0.1.2"

  on_macos do
    if Hardware::CPU.intel?
      url "https://github.com/ipriverdev/cli/releases/download/v0.1.2/cli_0.1.2_darwin_amd64.tar.gz"
      sha256 "edcf14ed805044241e4dbf58ebfebd44a42d0fbdda866fe8befa3a4b8aff6b10"

      define_method(:install) do
        bin.install "ipriver"
        bin.install_symlink "ipriver" => "ipr"
      end
    end
    if Hardware::CPU.arm?
      url "https://github.com/ipriverdev/cli/releases/download/v0.1.2/cli_0.1.2_darwin_arm64.tar.gz"
      sha256 "7917b40135db0104630b296ecf9bb5af2865217822c8ff976da09c607c635e42"

      define_method(:install) do
        bin.install "ipriver"
        bin.install_symlink "ipriver" => "ipr"
      end
    end
  end

  on_linux do
    if Hardware::CPU.intel? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipriverdev/cli/releases/download/v0.1.2/cli_0.1.2_linux_amd64.tar.gz"
      sha256 "73cae4688bb0f85270ecae1c5ba1aecb04f634075203da1cbef64271e1a4e97a"
      define_method(:install) do
        bin.install "ipriver"
        bin.install_symlink "ipriver" => "ipr"
      end
    end
    if Hardware::CPU.arm? && Hardware::CPU.is_64_bit?
      url "https://github.com/ipriverdev/cli/releases/download/v0.1.2/cli_0.1.2_linux_arm64.tar.gz"
      sha256 "957b2f2bd9dade19c60663da4c689e442ee322c8425c5adc6caf8f3dde7daedc"
      define_method(:install) do
        bin.install "ipriver"
        bin.install_symlink "ipriver" => "ipr"
      end
    end
  end

  test do
    system "#{bin}/ipriver", "version"
  end
end
